<a href="https://colab.research.google.com/github/Jaikirao/-Evaluating-the-Privacy-of-a-Function/blob/master/evaluating_privacy_of_a_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch

# the number of entries in our database
num_entries = 20

db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       dtype=torch.uint8)

In [0]:
def get_parallel_db(db , remove_index):
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [20]:
get_parallel_db(db,2)

tensor([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_dbs=list()
  for i in range(len(db)):
    pdb=get_parallel_db(db,i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs


In [22]:
get_parallel_dbs(db)

[tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [0]:
def create_db_and_parallel(num_enteries):
  db=torch.rand(num_enteries)>0.5
  pdbs= get_parallel_dbs(db)
  
  return db,pdbs

In [0]:
db,pdbs =create_db_and_parallel(10)

In [34]:
db

tensor([1, 1, 1, 1, 0, 1, 1, 0, 1, 0], dtype=torch.uint8)

In [35]:
pdbs

[tensor([1, 1, 1, 0, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 1, 0, 1], dtype=torch.uint8)]

In [0]:
db, pdbs = create_db_and_parallel(5000)

In [0]:
def query(db):
    return db.sum()

In [0]:
full_db_result = query(db)

In [0]:
sensitivity = 0
for pdb in pdbs:
    pdb_result = query(pdb)
    
    db_distance = torch.abs(pdb_result - full_db_result)
    
    if(db_distance > sensitivity):
        sensitivity = db_distance

In [41]:
sensitivity

tensor(1)

In [0]:
db, pdbs = create_db_and_parallel(5000)

In [0]:
full_db_result = query(db)

In [0]:
def sensitivity(query,n_enteries=1000):
  db, pdbs = create_db_and_parallel(n_enteries)
  full_db_result = query(db)
  max_distance = 0
  for pdb in pdbs:
    
    pdb_result = query(pdb)
    
    db_distance = torch.abs(pdb_result - full_db_result)
    
    if(db_distance > max_distance):
        max_distance = db_distance
  return max_distance

In [0]:
def query(db):
    return db.float().mean()

In [46]:
sensitivity(query)

tensor(0.0005)

In [47]:
db, pdbs = create_db_and_parallel(10)
db

tensor([1, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8)

In [48]:
pdbs

[tensor([1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 0, 0, 1], dtype=torch.uint8)]